import { defineStore } from 'ui.vue3.pinia';

export const dataStore = defineStore('data', {
  state: () => ({
    controls: [
      {
        id: 'id1',
        property: 'text',
        name: 'NUM',
        label: 'Case number',
        value: '',
        multi: 3,
        required: false,
        disabled: false,
      },
      {
        id: 'id2',
        property: 'tel',
        name: 'NUM',
        label: 'Phone number',
        value: '',
        multi: 3,
        required: false,
        disabled: false,
      },
      {
        id: 'id3',
        property: 'email',
        name: 'NUM',
        label: 'Your email',
        value: '',
        multi: 3,
        required: false,
        disabled: false,
      },
      {
        id: 'id4',
        property: 'hidden',
        name: 'NUM',
        value: '',
        required: false,
        disabled: false,
      },
      {
        property: 'hint',
        id: 'id5',
        name: 'OBJECT',
        label: 'ORNZ',
        value: '',
        count: 3,
        action: 'twinpx:ornz-hint',
        required: false,
        disabled: false,
      },
      {
        property: 'password',
        id: 'id6',
        name: 'PASSWORD',
        label: 'Password',
        value: '',
        required: false,
        disabled: false,
      },
      {
        property: 'date',
        type: 'range',
        id: 'id7',
        label: 'Calendar',
        name: 'DATE',
        required: true,
        value: ['20.02.2024', '28.02.2024'],
      },
      {
        property: 'date',
        type: 'single',
        id: 'id8',
        label: 'Calendar',
        name: 'DATE',
        required: true,
        value: '28.02.2024',
        hint_external: 'Hint',
        dependency: 'id6',
      },
      {
        property: 'select',
        type: 'radio',
        id: 'id9',
        name: 'SELECT_BUTTON_TEXT',
        label: 'Buttons',
        options: [
          {
            label: 'Thin',
            code: '1',
          },
          {
            label: 'Thick',
            code: '2',
          },
          {
            label: 'Uppercase',
            code: '3',
          },
        ],
        value: '2',
      },
      {
        property: 'checkbox',
        type: 'checkbox',
        id: 'id10',
        name: 'DEPENDENCY_CHECKBOX',
        required: false,
        label: 'Checkbox',
        value: 'on',
        checked: true,
        disabled: false,
        hint_external: 'Active checkbox',
      },
      {
        property: 'file',
        id: 'id11',
        name: 'FILE_LOGO',
        label: 'Logo',
        value: '',
        file: '',
        hint_external: 'For your site',
        required: true,
        disabled: false,
        accept: ['svg', 'png', 'jpg', 'jpeg'],
        image: true,
        multi: 5,
        maxsize: 10000000,
      },
      {
        property: 'file',
        type: 'upload',
        id: 'id12',
        name: 'FILE_LOGO',
        label: 'Upload logo',
        value: null,
        upload: {},
        hint_external: 'For your site',
        required: true,
        disabled: false,
        accept: ['svg', 'png', 'jpg', 'jpeg'],
        image: true,
        maxsize: 10000000,
      },
      {
        property: 'select',
        type: 'dropdown',
        id: 'id13',
        name: 'STATUS',
        label: 'Status',
        options: [
          {
            label: 'molestias',
            code: '23423423423',
          },
          {
            label: 'Farming',
            code: '324234324',
          },
          {
            label: 'Very',
            code: '324234325',
          },
        ],
        value: '',
        disabled: false,
      },
      {
        property: 'checkbox',
        type: 'switch',
        id: 'id14',
        name: 'SWITCH',
        required: false,
        label: 'labore',
        value: 'on',
        checked: true,
        disabled: false,
        hint_external: '',
        dependency: 'id6',
      },
    ],
  }),
});
